<?php
session_start();
 $error = '';
 $step = filter_input(INPUT_GET, 'step', FILTER_VALIDATE_INT) ?: 1;

if ($step > 1 && !isset($_SESSION['db_config'])) { 
    header('Location: index.php?step=1'); 
    exit; 
}
if ($step > 2 && !isset($_SESSION['site_config'])) { 
    header('Location: index.php?step=1'); 
    exit; 
}

if ($step === 6) {
    $dbConfig = $_SESSION['db_config'];
    $siteConfig = $_SESSION['site_config'];
    
    try {
        $configContent = "<?php\n// Generated by WinPass Installer\n";
        $configContent .= "define('DB_HOST', '{$dbConfig['host']}');\n";
        $configContent .= "define('DB_NAME', '{$dbConfig['name']}');\n";
        $configContent .= "define('DB_USER', '{$dbConfig['user']}');\n";
        $configContent .= "define('DB_PASS', '{$dbConfig['pass']}');\n";
        $configContent .= "define('SITE_URL', '{$siteConfig['url']}');\n";
        $configContent .= "define('SITE_NAME', '{$siteConfig['name']}');\n";
        $configContent .= "define('SECRET_KEY', '" . bin2hex(random_bytes(32)) . "');\n";
        $configContent .= "define('MAIL_HOST', 'smtp.example.com');\n";
        $configContent .= "define('MAIL_USER', 'user@example.com');\n";
        $configContent .= "define('MAIL_PASS', 'password');\n";
        $configContent .= "define('MAIL_PORT', 587);\n";
        $configContent .= "define('MAIL_FROM', 'noreply@winpass.tn');\n";
        $configContent .= "define('MAIL_FROM_NAME', 'WinPass');\n";
        
        if (file_put_contents('../includes/config.php', $configContent)) {
            require_once '../core/Database.php';
            $db = new Core\Database();
            $hashedPassword = password_hash($siteConfig['admin_pass'], PASSWORD_DEFAULT);
            $db->query("INSERT INTO utilisateurs (nom, prenom, email, password, type, statut) VALUES (?, ?, ?, ?, ?, 'actif')", 
                ['Admin', 'WinPass', $siteConfig['admin_email'], $hashedPassword, 'admin']);
            $success = true;
        } else {
            $error = "Impossible d'écrire le fichier de configuration. Vérifiez les permissions du dossier 'includes/'.";
        }
    } catch (Exception $e) {
        $error = "Erreur lors de la création de la configuration: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Installation WinPass Advanced</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="bg-gray-100 flex items-center justify-center min-h-screen">
    <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-2xl">
        <h1 class="text-3xl font-bold text-center mb-6 text-winpass-blue">Installation de WinPass Advanced</h1>
        <?php if ($error): echo "<div class='bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4'>$error</div>"; endif; ?>
        <?php if ($step === 6 && isset($success)): ?>
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-4">Succès ! WinPass Advanced a été installé.</div>
            <p class="text-center mb-4 font-bold text-red-600">TRÈS IMPORTANT : Supprimez le dossier <code>install/</code> de votre serveur.</p>
            <div class="text-center"><a href="../public/index.php" class="bg-winpass-blue text-white font-bold py-2 px-4 rounded">Aller sur mon site</a></div>
        <?php else: ?>
            <div class="mb-6">
                <div class="flex justify-between mb-2">
                    <span>Étape <?php echo $step; ?> sur 5</span>
                    <span><?php echo round(($step / 5) * 100); ?>%</span>
                </div>
                <div class="w-full bg-gray-200 rounded-full h-2.5">
                    <div class="bg-winpass-blue h-2.5 rounded-full" style="width: <?php echo round(($step / 5) * 100); ?>%"></div>
                </div>
            </div>
            <?php include "steps.php"; ?>
        <?php endif; ?>
    </div>
</body>
</html>
